apiVersion: v1
kind: Pod
metadata:
  name: cluster-pod-2
  labels:
    app: segundo-pod
spec:
  containers:
    - name: container-pod-2
      image: nginx:stable
      ports:
        - containerPort: 80