apiVersion: v1
kind: Pod
metadata:
  name: db-noticias-pod
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-noticias-cm
      #env:
      #  - name: MYSQL_ROOT_PASSWORD
      #    valueFrom:
      #      configMapKeyRef:
      #        name: db-noticias-cm
      #        key: MYSQL_ROOT_PASSWORD
      #  - name: MYSQL_DATABASE
      #    valueFrom:
      #      configMapKeyRef:
      #        name: db-noticias-cm
      #        key: MYSQL_DATABASE
      #  - name: MYSQL_PASSWORD
      #    valueFrom:
      #      configMapKeyRef:
      #        name: db-noticias-cm
      #        key: MYSQL_PASSWOR#D